# ~/.bashrc, ~/.zshrc require these
alias cp='cp -i'
alias mv='mv -i'
alias rm='rm -i'
alias ls='ls -F --color=auto'
alias ll='ls -l'
alias lh='ls -l -h'
alias la='ls -a'
alias grep='grep --color=auto'
alias em='emacsclient -a emacs --no-wait'
alias cl='clear'
alias l='less'
alias ..='cd ..'
alias p='pushd'
alias py='python'
alias fm='free -m'
