# ~/.bashrc, ~/.zshrc require these
alias ..='cd ..'
alias cl='clear'
alias cp='cp -i'
alias em='emacsclient -a emacs --no-wait'
alias fm='free -m'
alias grep='grep --color=auto'
alias la='ls -a'
alias lh='ls -l -h'
alias l='less'
alias ll='ls -l'
alias ls='ls -F --color=auto'
alias mv='mv -i'
alias p='pushd'
alias py='python'
alias rm='rm -i'
alias up='uptime'
